import { Hero } from "@/components/Hero";
import { Services } from "@/components/Services";
import { Container } from "@chakra-ui/layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Digital Lil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" maxW="1400px">
        <Hero />
        <Services />
      </Container>
    </>
  );
}
